import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const space_Mono = Space_Mono({ subsets: ["latin"],weight:'700' });

export const metadata: Metadata = {
  title: "Shohidul Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_Mono.className}>{children}</body>
    </html>
  );
}
